fzone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView 
from . import views


urlpatterns = [
    path('retro/', views.retro,name='retro'),
    path('videojuegos/', views.videojuegos,name='videojuegos'),
    path('consolas/', views.consolas,name='consolas'),
    path('tcg/', views.tcg,name='tcg'),
    path('', views.ini.as_view(),name='inicio'),
    path('figuras/', views.figuras,name='figuras'),
    path('admin/', admin.site.urls),
    path('cliente/',include('cliente.urls')),
    path('game/',include('game.urls')),
    path('console/',include('console.urls')),

]

urlpatterns +={
    path('accounts/',include('django.contrib.auth.urls')),
}

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
from django.urls import path
from .views import *

app_name='game'

urlpatterns = [
    path('',IndexView.as_view(), name='allgame'),
    path('nsw/', SwitchGame.as_view(), name='nswgame'),
    path('ps4/', PS4Game.as_view(), name='ps4game'),
    path('xbo/', XBOGame.as_view(), name='xbogame'),
    path('<str:pk>/', DetailView.as_view(), name='details'),
    #path(r'^', VGUpdate, name='Editar'),
    path(r'mantenedor/editar/<pk>/', VGUpdate, name='editar'),
    path('mantenedor/create/', VGCreate, name='createVG'),
    path('mantenedor/buscar/', VGSearch, name='serchVG'),
    path(r'mantenedor/Eliminar/<pk>/', VGDelete, name='eliminar'),
]

game/models.py
from django.db import models
from django.urls import reverse
import uuid

#Videogames
# Create your models here.
class Genre(models.Model):
    #campos
    gen_desc=models.CharField(max_length=100,help_text="Ingrese Descripcion del genero")

    #metodos
    def __str__(self):
        return self.gen_desc

class IdiomaTx(models.Model):
    #campos
    lang_desc=models.CharField(max_length=100,help_text="Ingrese Descripcion del idioma")

    #metodos
    def __str__(self):
        return self.lang_desc

class IdiomaAu(models.Model):
    #campos
    lang_desc=models.CharField(max_length=100,help_text="Ingrese Descripcion del idioma")

    #metodos
    def __str__(self):
        return self.lang_desc

class VG(models.Model):

    #campos
    vg_id=models.CharField(max_length=10,help_text="Ingrese ID del Juego",primary_key="True")
    vg_nom=models.CharField(max_length=100,help_text="Ingrese Nombre del Juego")
    vg_price=models.IntegerField(help_text="Ingrese el precio del juego (Ej: $ 999 999).")
    vg_descr=models.TextField(max_length=3000, help_text="Ingrese la descripcion del juego.")
    vg_prev=models.BooleanField(null=True)
    vg_online=models.BooleanField(null=True)
    vg_online_plyr=models.IntegerField(help_text="Ingrese La cantidad de jugadores online.")
    vg_local_plyr=models.IntegerField(help_text="Ingrese La cantidad de jugadores local (Ej: 1).")

    vg_main_img=models.ImageField(upload_to="gallery", null=True)
    vg_img2=models.ImageField(upload_to="gallery", null=True)
    vg_img3=models.ImageField(upload_to="gallery", null=True)
    vg_img4=models.ImageField(upload_to="gallery", null=True)

    vg_dev=models.ForeignKey('Dev', on_delete=models.SET_NULL, null=True)
    vg_pub=models.ForeignKey('Pub', on_delete=models.SET_NULL, null=True)
    vg_rating=models.ForeignKey('Rating', on_delete=models.SET_NULL, null=True)
    vg_plat=models.ForeignKey('Plat', on_delete=models.SET_NULL, null=True)
    
    vg_gen=models.ManyToManyField(Genre)
    vg_tx_lang=models.ManyToManyField(IdiomaTx)
    vg_audio_lang=models.ManyToManyField(IdiomaAu)

    vg_banner=models.ImageField(upload_to="gallery", null=True, blank=True)

    #metodos
    def __str__(self):
        return self.vg_nom

    def get_absolute_url(self):
        return reverse('game:details', args=[str(self.vg_id)])

class VGInstance(models.Model):
    inst_id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='ID para esta unidad')
    inst_vg = models.ForeignKey('VG', on_delete=models.SET_NULL, null=True)
    inst_on_stock = models.BooleanField(null=True)

    class Meta:
        ordering = ['inst_id']

    def __str__(self):
        return f'{self.inst_id} ({self.inst_vg.vg_nom})'


class Dev(models.Model):

    #campos
    dev_nom=models.CharField(max_length=100,help_text="Ingrese Nombre del Desarrollador")

    #metodos
    def __str__(self):
        return self.dev_nom

class Pub(models.Model):
    #campos
    pub_nom=models.CharField(max_length=100,help_text="Ingrese Nombre del Distribuidor")

    #metodos
    def __str__(self):
        return self.pub_nom

class Rating(models.Model):
    #campos
    ratng_desc=models.CharField(max_length=100,help_text="Ingrese Descripcion de la calificacion")

    #metodos
    def __str__(self):
        return self.ratng_desc

class Plat(models.Model):
    #campos
    plat_nom=models.CharField(max_length=100,help_text="Ingrese Nombre de la plataforma")

    #metodos
    def __str__(self):
        return self.plat_nom

class Banner(models.Model):
    __instance = None
    ban_id=models.CharField(max_length=10,help_text="Ingrese ID del Banner",primary_key="True")
    ban_vg=models.ManyToManyField(VG)
    
    def __str__(self):
        return self.ban_id
    

game/forms.py
from django import forms

from .models import VG,Dev,Genre,IdiomaAu,IdiomaTx,Plat,Pub,Rating

class VGCreateForm(forms.ModelForm):
    vg_id = forms.CharField(label="ID", required=True,
                widget=forms.TextInput(
                        attrs={
                            "placeholder":"Ingrese la id del videojuego",
                            "minlength":3
                        }
                )   
            )
    vg_nom = forms.CharField(label="Nombre Producto", required=True,
                widget=forms.TextInput(
                        attrs={
                            "placeholder":"Ingrese el nombre del videojuego",
                            "minlength":5
                        }
                )   
            )
    vg_price = forms.IntegerField(label="Precio", required =True,
                    widget=forms.NumberInput(
                        attrs={
                            "placeholder":"Precio Videojuego"
                        }
                    )
                )
    vg_descr = forms.CharField(label="Descripcion", required=True,
                widget=forms.Textarea(
                        attrs={
                            "placeholder":"Ingrese el nombre del videojuego",
                            "minlength":5,
                            "maxlength":3000
                        }
                )   
            )
    vg_prev = forms.BooleanField(label="Preventa", required=False)
    vg_online = forms.BooleanField(label="Multijugador Online", required=False)
    vg_online_plyr = forms.IntegerField(label="Jugadores Online", required =True,
                    widget=forms.NumberInput(
                        attrs={
                            "placeholder":"Numero de jugadores Online"
                        }
                    )
                )
    vg_local_plyr = forms.IntegerField(label="Jugadores Locales", required =True,
                    widget=forms.NumberInput(
                        attrs={
                            "placeholder":"Numero de jugadores Local"
                        }
                    )
                )

    vg_dev = forms.ModelChoiceField(queryset=Dev.objects.all(),label="Desarrolladora",required=True)
    vg_pub = forms.ModelChoiceField(queryset=Pub.objects.all(),label="Distribuidora",required=True)
    vg_rating = forms.ModelChoiceField(queryset=Rating.objects.all(),label="Rating Edad",required=True)
    vg_plat = forms.ModelChoiceField(queryset=Plat.objects.all(),label="Plataforma",required=True)
    
    vg_gen = forms.ModelMultipleChoiceField(queryset=Genre.objects.all(),label="Plataforma",required=True)
    vg_tx_lang = forms.ModelMultipleChoiceField(queryset=IdiomaTx.objects.all(),label="Idiomas Texto",required=True)
    vg_audio_lang = forms.ModelMultipleChoiceField(queryset=IdiomaAu.objects.all(),label="Idioma Audio",required=True)
    
    vg_main_img = forms.ImageField(label="Imagen principal")
    vg_img2 = forms.ImageField(label="Imagen secundaria")
    vg_img3 = forms.ImageField(label="Imagen secundaria")
    vg_img4 = forms.ImageField(label="Imagen secundaria")
    class Meta:
        model = VG
        fields =[
            'vg_id',
            'vg_nom',
            'vg_price',
            'vg_descr',
            'vg_prev',
            'vg_online',
            'vg_online_plyr',
            'vg_local_plyr',
            'vg_dev',
            'vg_pub',
            'vg_rating',
            'vg_plat',
            'vg_gen',
            'vg_tx_lang',
            'vg_audio_lang',
            'vg_main_img',
            'vg_img2',
            'vg_img3',
            'vg_img4'
        ]

game/views.py
from django.shortcuts import render
from .models import VG
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from .forms import VGCreateForm

# Create your views here.
class IndexView(generic.ListView):
    model = VG
    template_name = 'game/vg_list.html'
    def get_queryset(self):
        return VG.objects.all() 

class SwitchGame(generic.ListView):
    model = VG
    template_name = 'game/vg_list.html'
    def get_queryset(self):
        return VG.objects.filter(vg_plat__plat_nom__iexact='Nintendo Switch')

class PS4Game(generic.ListView):
    model = VG
    template_name = 'game/vg_list.html'
    def get_queryset(self):
        return VG.objects.filter(vg_plat__plat_nom__iexact='PlayStation 4')

class XBOGame(generic.ListView):
    model = VG
    template_name = 'game/vg_list.html'
    def get_queryset(self):
        return VG.objects.filter(vg_plat__plat_nom__iexact='Xbox One')

class DetailView(generic.DetailView):
    model = VG

def VGCreate(request):
    form = VGCreateForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit = True)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
   
    context = {
        'title':"Crear",
        'form':form
    }
    return render(request,'game/vg_crear.html',context)

def VGSearch(request, id=None):

    queryset= VG.objects.all()
    query = request.GET.get("q")
    if query:
        queryset = queryset.filter(vg_id__icontains=query)
    context = {
        "object_list" : queryset,
        "title" : "Busca"
    }
    return render(request, "game/vg_buscar.html",context)


def VGUpdate(request, pk =None):
    instance = get_object_or_404(VG, vg_id = pk)
    form = VGCreateForm(request.POST or None, request.FILES or None,instance=instance)
    if form.is_valid():
        instance = form.save(commit=True)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "title": "Editar",
        "instance":instance,
        "form" : form
    }
    return render(request, "game/vg_crear.html",context)


def VGDelete(request, pk= None):
    instance = get_object_or_404(VG, vg_id = pk)
    instance.delete()
    return redirect("game:serchVG")

templates/game/lateral_bar.html
<div class="col-lg-2 d-none d-lg-table-cell">
        <div class="list-group">
            <a class="list-group-item nav-link" href="{% url 'game:createVG' %}">Crear</a>
            <a class="list-group-item nav-link" href="{% url 'game:serchVG' %}">Listar</a>
        </div>
</div>

templates/game/vg_buscar.html
{% extends "main_template.html" %}
{% load humanize %}
{% block content %}
<div class="container">
  <div class="row">
    {% include 'game/lateral_bar.html' %}
    <div class="col-lg-10">
      <div class="card-body">
          <h3 class="card-title">Mantenedor de videojuegosVideojuegos</h3>
          <h4>{{ titulo|title  }} un Videojuego</h4>
          <form method="GET" action="">
              <input type="text" name="q" placeholder="Introduzca la Id del videojuego" >
              <input type="submit" name="Serch" value = "{{ title }}">

          </form>

      </div>
      <table class="table">
        <thead>
        <tr>
          <th>Id</th>
          <th>Nombre</th>
          <th>Consola</th>
          <th>Opciones</th>
        </tr>
        </thead>
        
        <tbody>
          
          {% for object in object_list %}
          <tr>
            <th scope="row">{{ object.vg_id }}</th>
            <td>{{ object.vg_nom }}</td>
            <td>{{ object.vg_plat }}</td>
            <td>
              <a href="{{ object.get_absolute_url }}" class="btn btn-secondary" >Mostrar</a>
              <a href="{% url 'game:editar' pk=object.vg_id %}" class="btn btn-secondary" >Editar</a>
              <a href="{% url 'game:eliminar' pk=object.vg_id %}" class="btn btn-secondary" >Eliminar</a>
            </td>
          </tr>

          {% endfor %}
          
        </tbody>
      </table>
    </div> 
  </div>
</div>
{% endblock %}

templates/game/vg_crear.html
{% extends "main_template.html" %}
{% load humanize %}
{% block content %}
<div class="container">
    <div class="row">
        {% include 'game/lateral_bar.html' %}
        <div class="col-lg-9">
            
            <div class="card-body">
                <h3 class="card-title">Mantenedor de videojuegosVideojuegos</h3>
                <h4>{{ titulo|title  }} un Videojuego</h4>
                <h4>Ingresar los datos</h4>
                <p id="error"> Porfavor Corrija las casillas marcadas en rojo</p>
                <p id="succes"> La Información se Envió correctamente, por favor verifique si E-mail.</p>
                <div class="tab-pane fade show active" id="usr" role="tabpanel" aria-labelledby="home-tab">
                    <form enctype="multipart/form-data" method="POST">{% csrf_token %} 
                        
                        {{ form.as_p }}
                        
                        <input type="submit" value="{{ title }}"> 
                    </form>
                
                </div>
            </div>
        </div>
    </div> 
</div>
{% endblock %}|

templates/game/vg_detail.html
{% extends "main_template.html" %}
{% load humanize %}
{% block content %}
<div class="container">
        
    <!--Zona de productos relacionados-->
    <div class="row">
            <div class="col-lg-3 d-none d-lg-table-cell">
                    <h2 class="my-4" style="text-align: center">Productos relacionados</h2>
                    <div class="list-group">
                      <a href="kirbysa.html" class="list-group-item">
                        <p style="text-align: center;">{% load static %}<img src="{% static 'img/game/cover/kirbysa.jpg' %}" alt="kirbycover" width="100"><br>
                          Kirby Star Allies<br> (Nintendo Switch)<br>
                        $49.990</p>
                      </a>
                      <a href="zeldalaw.html" class="list-group-item">
                          <p style="text-align: center;"><img src="{% static 'img/game/cover/zeldalinkawpre.jpg' %}" alt="zeldacover" width="100"><br>
                            The Legend of Zelda:<br> Link's Awakening <br> (Nintendo Switch)<br>
                          $59.990</p>
                      </a>
                      <a href="ys8sw.html" class="list-group-item">
                        <p style="text-align: center;"><img src="{% static 'img/game/cover/ys8nsw.png' %}" alt="ys8cover" width="100"><br>
                          YS VIII<br>Lacrimosa Of Dana <br> (Nintendo Switch)<br>
                        $49.990</p>
                      </a>
                    </div>
        </div>

    <!--MAIN-->
    <div class="col-lg-9">

        <!--CARRUSEL-->
        <div class="card mt-4">
            <div id="demo" class="carousel slide" data-ride="carousel">

                <!-- Indicators -->
                <ul class="carousel-indicators">
                    <li data-target="#demo" data-slide-to="0" class="active"></li>
                    <li data-target="#demo" data-slide-to="1"></li>
                    <li data-target="#demo" data-slide-to="2"></li>
                    <li data-target="#demo" data-slide-to="3"></li>
                </ul>
        
                <!-- The slideshow -->
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{{ object.vg_main_img.url }}" alt="Imagen Principal" style="width:100%">
                    </div>
                    <div class="carousel-item">
                        <img src="{{ object.vg_img2.url }}" alt="Gameplay 1 de Valkyria Chronicles 4" style="width:100%">
                    </div>
                    <div class="carousel-item">
                        <img src="{{ object.vg_img3.url }}" alt="Gameplay 2 de Valkyria Chronicles 4" style="width:100%;">
                    </div>
                    <div class="carousel-item">
                        <img src="{{ object.vg_img4.url }}" alt="Gameplay 3 de Valkyria Chronicles 4" style="width:100%;">
                    </div>
                </div>
        
                <!-- Left and right controls -->
                <a class="carousel-control-prev" href="#demo" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </a>
            </div>
        </div>

        <!--TEXTO DE PROD-->
        <div class="card-body">
            <h3 class="card-title">{{ object.vg_nom }} ({{ object.vg_plat }})</h3>
            <h4>${{ object.vg_price|intcomma }}</h4>
            <button type="button" class="btn btn-secondary" id="agregar" onclick="cambio()">Agregar al carrito</button>
            <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
            4.0 stars
            <div class="row-sm1">
                <h4><br></h4>
            </div>
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#descr" role="tab" aria-controls="descr" aria-selected="true">Descripción</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#spec" role="tab" aria-controls="spec" aria-selected="false">Especificaciones</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#rev" role="tab" aria-controls="rev" aria-selected="false">Reseñas</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="descr" role="tabpanel" aria-labelledby="home-tab">
                    <p class="card-text">
                        {{ object.vg_descr }}
                    </p>
                </div>
                <div class="tab-pane fade" id="spec" role="tabpanel" aria-labelledby="profile-tab">
                        <table class="table table-striped">
                                <tbody>
                                    <tr>
                                        <td><b>Desarrollador</b></td>
                                        <td>{{ object.vg_dev }}</td>
                                    </tr>
                                    <tr>
                                        <td><b>Distribuidor</b></td>
                                        <td>{{ object.vg_pub }}</td>
                                    </tr>
                                    <tr>
                                        <td><b>Consola</b></td>
                                        <td>{{ object.vg_plat }}</td>
                                    </tr>
                                    <tr>
                                        <td><b>Género</b></td>
                                        <td>{{ object.vg_gen.all|join:", " }}</td>
                                    </tr>
                                    <tr>
                                      <td><b>Clasificación de Edad</b></td>
                                      <td>{{ object.vg_rating }}</td>
                                    </tr>
                                    <tr>
                                      <td><b>Idioma de textos</b></td>
                                        <td>{{ object.vg_tx_lang.all|join:", " }}</td>
                                      </tr>
                                    <tr>
                                      <td><b>Idioma de Voces</b></td>
                                      <td>{{ object.vg_audio_lang.all|join:", " }}</td>
                                    </tr>
                                </tbody>
                            </table>
                </div>
                <div class="tab-pane fade" id="rev" role="tabpanel" aria-labelledby="contact-tab">
                    <div class="card card-outline-secondary my-4">
                        <div class="card-header">
                            Reseñas del producto
                        </div>
                        <div class="card-body">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                            <hr>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                            <hr>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                            <hr>
                            <a href="#" class="btn btn-success">Deja tu reseña</a>
                        </div>
                    </div>
                </div>
        </div>

    </div>

</div>
</div>
</div>
{% endblock %}

templates/game/vg_list.html
{% extends "main_template.html" %}
{% load humanize %}
{% block content %}
<div class="container" style="margin-top: 20px">
    <div class="row">
            {% for VG in object_list %}
                <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                          {% load static %}<a href="{{ VG.get_absolute_url }}"><img src="{{ VG.vg_main_img.url }}" alt="YS8SW" class ="imagenresp" style="width: 100%;"></a>
                          <div class="card-body">
                            <h4 class="card-title">
                              <a href="{{ VG.get_absolute_url }}">{{ VG.vg_nom }}</a>
                            </h4>
                            <h6>{{ VG.vg_plat }}</h6>
                            <h5>${{ VG.vg_price|intcomma }}</h5>
                            <p class="card-text"></p>
                          </div>
                          <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                          </div>
                        </div>
                      </div>
            {% endfor %}
    </div>
</div>
{% endblock %}