cliente/urls.py
from django.urls import path
from .views import *


app_name='cliente'

urlpatterns = [
    path('cuenta/create/',CuentaCreate, name='reg'),
    path('<str:pk>/', ProfileDetailView.as_view(), name = 'profile')
    #path('cuenta/create/',CuentaCreate.as_view(), name='reg')
]

console/urls.py
from django.urls import path
from .views import *

app_name = 'console'

urlpatterns = [
    path('',IndexView.as_view(), name='allconsole'),
    path('<str:pk>/', DetailView.as_view(), name='details'),
]

fzone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView 
from . import views


urlpatterns = [
    path('retro/', views.retro,name='retro'),
    path('videojuegos/', views.videojuegos,name='videojuegos'),
    path('consolas/', views.consolas,name='consolas'),
    path('tcg/', views.tcg,name='tcg'),
    path('', views.ini.as_view(),name='inicio'),
    path('figuras/', views.figuras,name='figuras'),
    path('admin/', admin.site.urls),
    path('cliente/',include('cliente.urls')),
    path('game/',include('game.urls')),
    path('console/',include('console.urls')),

]

urlpatterns +={
    path('accounts/',include('django.contrib.auth.urls')),
}

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
from django.urls import path
from .views import *

app_name='game'

urlpatterns = [
    path('',IndexView.as_view(), name='allgame'),
    path('nsw/', SwitchGame.as_view(), name='nswgame'),
    path('ps4/', PS4Game.as_view(), name='ps4game'),
    path('xbo/', XBOGame.as_view(), name='xbogame'),
    path('<str:pk>/', DetailView.as_view(), name='details'),
    #path(r'^', VGUpdate, name='Editar'),
    path(r'mantenedor/editar/<pk>/', VGUpdate, name='editar'),
    path('mantenedor/create/', VGCreate, name='createVG'),
    path('mantenedor/buscar/', VGSearch, name='serchVG'),
    path(r'mantenedor/Eliminar/<pk>/', VGDelete, name='eliminar'),
]

templates/consolas.html
{% extends "main_template.html" %}
{% block content %}

<title> Consolas | Freak Zone Store </title>
<div class="container" style="margin-top: 20px">
    <div class="row">

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#">{% load static %}<img src="{% static 'img/console/switchfront.jpg' %}" alt="nintendo switch" class ="imagenresp" style="width: 100%;"></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Consola Nintendo Switch 32GB</a>
                  </h4>
                  <h5>$299.990</h5>
                  <p class="card-text"></p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>
  
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img src="{% static 'img/console/ps4profront.jpg' %}" alt="playstation 4 pro" class="imagenresp" style="width: 100%;"></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Consola PlayStation 4 Pro 1TB</a>
                  </h4>
                  <h5>$449.990</h5>
                  <p class="card-text"></p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>
  
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img src="{% static 'img/console/xbonexfront.jpg' %}" alt="xbox one x" class="imagenresp" style="width: 100%;"></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Consola Xbox One X 1TB</a>
                  </h4>
                  <h5>$449.990</h5>
                  <p class="card-text"></p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img src="{% static 'img/console/2dsfront.jpg' %}" alt="nintendo 2ds" class="imagenresp" style="width: 100%;"></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Consola Nintendo 2DS XL</a>
                  </h4>
                  <h5>$179.990</h5>
                  <p class="card-text"></p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>
  
          </div>
          <!-- /.row -->
    </div>
    {% endblock %}

templates/consolasRetro.html
{% extends "main_template.html" %}
{% block content %}

<title>Consolas Retro | Freak Zone Store</title>

<div class="container" style="margin-top: 20px">
    <div class="row">

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#">{% load static %}<img src="{% static 'img/retro/nesfront.png' %}" alt="NES Classic" class ="imagenresp" style="width: 100%;"></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Consola Nintendo NES Classic Edition</a>
                  </h4>
                  <h6>Nintendo</h6>
                  <h5>$79.990</h5>
                  <p class="card-text"></p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                  <a href="#"><img src="{% static 'img/retro/snesfront.png' %}" alt="SNES Classic" class ="imagenresp" style="width: 100%;"></a>
                  <div class="card-body">
                    <h4 class="card-title">
                      <a href="#">Consola Super Nintendo Mini Classic Edition</a>
                    </h4>
                    <h6>Nintendo</h6>
                    <h5>$129.990</h5>
                    <p class="card-text"></p>
                  </div>
                  <div class="card-footer">
                    <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                  </div>
                </div>
              </div>

            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                  <a href="#"><img src="{% static 'img/retro/ps1front.jpg' %}" alt="PS1 Classic" class ="imagenresp" style="width: 100%;"></a>
                  <div class="card-body">
                    <h4 class="card-title">
                      <a href="#">Consola PlayStation Classic</a>
                    </h4>
                    <h6>Sony</h6>
                    <h5>$54.990</h5>
                    <p class="card-text"></p>
                  </div>
                  <div class="card-footer">
                    <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                  </div>
                </div>
              </div>

          </div>
      </div>
      {% endblock %}

templates/inicio.html
{% extends "main_template.html" %}
{% block content %}
<!--Columna de destacados-->
<title>Inicio | Freak Zone Store</title>

<div class="container">
    <div class="row">
        <div class="col-lg-3 d-none d-lg-table-cell" style="margin-left: 40px">
            <h2 class="my-4" style="text-align: center"><b>Destacados</b></h2>
            <div class="list-group">
              <a href="{% url 'figuras' %}" class="list-group-item">
                <p style="text-align: center;">{% load static %}<img alt="imagen figuras" src="{% static 'img/main/figcol.jpg' %}" style="width:100%"><br>
                 ¡Nuevo stock en figuras! 
                </p>
              </a>
              <a href="{% url 'console:allconsole' %}" class="list-group-item">
                  <p style="text-align: center;"><img src="{% static 'img/main/concol.jpg' %}" alt="imagen consolas" style="width:100%"><br>
                    ¡Nuevo stock en consolas!
                  </p>
              </a>
              <a href="{% url 'game:allgame' %}" class="list-group-item">
                  <p style="text-align: center;"><img src="{% static 'img/main/colgame.png' %}" alt="imagen juegos" style="width:100%"><br>
                    ¡Nuevo stock en videojuegos!
                  </p>
              </a>

              <a href="{% url 'tcg' %}" class="list-group-item">
                  <p style="text-align: center;"><img src="{% static 'img/main/coltcg.png' %}" alt="imagen tcg" style="width:100%"><br>
                    ¡Nuevo stock en TCG!
                </p>
              </a>
            </div>
      </div>

      <!--Sección para el carrusel-->
        <div class="col-lg-8">
          <div class="container">
            <!--CARRUSEL-->
                    <div class="card mt-4">
              <div id="demo" class="carousel slide" data-ride="carousel">

              <!-- Indicators -->
              <ul class="carousel-indicators">
                <li data-target="#demo" data-slide-to="0" class="active"></li>
                <li data-target="#demo" data-slide-to="1"></li>
                <li data-target="#demo" data-slide-to="2"></li>
                <li data-target="#demo" data-slide-to="3"></li>
              </ul>
      
              <!-- The slideshow -->
              {% for Banner in object_list %}
              <div class="carousel-inner">
                  <div class="carousel-item active">
                      <a href="#"><img alt="banner" src="{% static 'img/main/main.png' %}"  style="width:100%;"></a>
                    </div>
                {% for VG in Banner.ban_vg.all %}
                  <div class="carousel-item">
                    <a href="{{ VG.get_absolute_url }}"><img alt="banner" src="{{ VG.vg_banner.url }}"  style="width:100%;"></a>
                  </div>
                {% endfor %}
                </div>
              {% endfor %}
      
                <!-- Left and right controls -->
                <a class="carousel-control-prev" href="#demo" data-slide="prev">
                  <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#demo" data-slide="next">
                  <span class="carousel-control-next-icon"></span>
                </a>
              </div>
            </div>
            <div class="row">
              <p></p>
            </div>

            <!--Cositas de abajo del container-->
          <div class="row">

                <div class="col-lg-4 col-md-6 mb-4">
                  <div class="card h-100">
                    <a href="#"><img src="{% static 'img/main/ps4front.png' %}" alt="imagen principal ps4"  class ="imagenresp" style="width: 100%;"></a>
                    <div class="card-body">
                      <h4 class="card-title">
                        <a href="#">PlayStation 4</a>
                      </h4>
                        <ul>
                          <li>
                            <a href="#">Consolas</a>
                          </li>
                          <li>
                            <a href="#">Accesorios</a>
                          </li>
                          <li>
                            <a href="{% url 'game:ps4game' %}">Juegos</a>
                          </li>
                        </ul>
                    </div>
                  </div>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                      <a href="#"><img src="{% static 'img/main/nswfront.png' %}" alt="imagen principal nintendo switch"  class ="imagenresp" style="width: 100%;"></a>
                      <div class="card-body">
                        <h4 class="card-title">
                          <a href="#">Nintendo Switch</a>
                        </h4>
                          <ul>
                            <li>
                              <a href="#">Consolas</a>
                            </li>
                            <li>
                              <a href="#">Accesorios</a>
                            </li>
                            <li>
                              <a href="{% url 'game:nswgame' %}">Juegos</a>
                            </li>
                          </ul>
                      </div>
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                      <div class="card h-100">
                        <a href="#"><img src="{% static 'img/main/xbofront.png' %}" alt="imagen principal xbone" class ="imagenresp" style="width: 100%;"></a>
                        <div class="card-body">
                          <h4 class="card-title">
                            <a href="#">Xbox One</a>
                          </h4>
                            <ul>
                              <li>
                                <a href="#">Consolas</a>
                              </li>
                              <li>
                                <a href="#">Accesorios</a>
                              </li>
                              <li>
                                <a href="{% url 'game:xbogame' %}">Juegos</a>
                              </li>
                            </ul>
                        </div>
                      </div>
                    </div>
                  
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                          <a href="{% url 'figuras' %}"><img src="{% static 'img/main/figurfront.png' %}" alt="imagen principal figuras" class ="imagenresp" style="width: 100%;"></a>
                          <div class="card-body">
                            <h4 class="card-title">
                              <a href="{% url 'figuras' %}">Figuras</a>
                            </h4>
                              <ul>
                                <li>
                                  <a href="#">Funko POP</a>
                                </li>
                                <li>
                                  <a href="#">Otros</a>
                                </li>
                              </ul>
                           </div>
                         </div>
                    </div>

                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                          <a href="{% url 'tcg' %}"><img src="{% static 'img/main/tcgfront.png' %}" alt="imagen principal tcg" class ="imagenresp" style="width: 100%;"></a>
                          <div class="card-body">
                            <h4 class="card-title">
                              <a href="{% url 'tcg' %}">TCG</a>
                            </h4>
                              <ul>
                                <li>
                                  <a href="#">Magic: The Gathering</a>
                                </li>
                                <li>
                                  <a href="#">Pokemon</a>
                                </li>
                                <li>
                                  <a href="#">Yu-Gi-Oh!</a>
                                </li>
                              </ul>
                           </div>
                         </div>
                    </div>

                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                          <a href="#"><img src="{% static 'img/main/retrofront.png' %}" alt="imagen principal retro" class ="imagenresp" style="width: 100%;"></a>
                          <div class="card-body">
                            <h4 class="card-title">
                              <a href="#">Retro</a>
                            </h4>
                              <ul>
                                <li>
                                  <a href="{% url 'retro' %}">Consolas</a>
                                </li>
                              </ul> 
                           </div>
                         </div>
                    </div>
              </div>
            </div>
          </div>
      </div>
    </div>

{% endblock %}

templates/main_template.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% load static %} <link rel="stylesheet" href="{% static '/vendor/bootstrap/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static '/allStyle.css' %}">
        <link rel="stylesheet" href="{% static '/css_profile.css' %}">
        <!-- Bootstrap core JavaScript -->
        <script src="{% static '/vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static '/vendor/bootstrap/js/bootstrap.js' %}"></script>
        <link rel="shortcut icon" href="{% static '/favicon.ico' %}" type="image/x-icon">
        <link rel="icon" href="{% static '/favicon.ico' %}" type="image/x-icon">
        <!-- scripts -->
        <script src="{% static 'vendor/jquery/script.js' %}"></script>
    </head>
    <body>
        <!--Aqui se encuentra la parte del header-->
        <div class="header" onload="loadCart()">
                <a href="{% url 'inicio' %}"><img src="{% static '/img/header/head2.png' %}" alt="logo de Freak Zone Store" style="text-align: center; width:50%;"></a>
                <div id="nav">
                    <ul class="parent">
                        <li style="width:15%" class="navli"><a href="{% url 'inicio' %}">Inicio</a></li>

                        <li style="width:10%" class="navli"><a href="{% url 'console:allconsole' %}">Consolas</a>
                            <ul class="child">
                                <li><a href="#">Nintendo Switch</a></li>
                                <li><a href="#">PlayStation 4</a></li>
                                <li><a href="#">Xbox One</a></li>
                                <li><a href="{% url 'retro' %}">Retro</a></li>
                            </ul>
                        </li>

                        <li style="width:10%" class="navli"><a href="{% url 'game:allgame' %}">Videojuegos</a>
                            <ul class="child">
                                <li><a href="{% url 'game:nswgame' %}">Nintendo Switch</a></li>
                                <li><a href="{% url 'game:ps4game' %}">PlayStation 4</a></li>
                                <li><a href="{% url 'game:xbogame' %}">Xbox One</a></li>
                            </ul>
                        </li>
                        <li style="width:8%" class="navli"><a href="{% url 'figuras' %}">Figuras</a>
                            <ul class="child">
                                <li><a href="#">Funko</a></li>
                                <li><a href="#">Otros</a></li>
                            </ul>
                        </li>
                        <li style="width:5%" class="navli"><a href="{% url 'tcg' %}">TCG</a>
                            <ul class="child">
                                <li><a href="#">Magic</a></li>
                                <li><a href="#">Pokemon</a></li>
                                <li><a href="#">Yu-Gi-Oh!</a></li>
                            </ul>
                        </li>
                        <li style="width:10%" class="navli"><div id="cart">Carrito (0)</div></li>
                        {% if user.is_authenticated %}
                            <li style="width:12%" class="navli"><a href="#">{{ user.get_username }}</a>
                                <ul class="child">
                                    <li><a href= "{{ user.cuenta.get_absolute_url }}">Profile</a></li>
                                    {% if user.is_superuser %}
                                        <li><a href="{% url 'game:serchVG' %}">Mantenedor</a></li>
                                    {% endif %}
                                    <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li style="width:5%" class="navli"><a href="{% url 'login'%}?next={{request.path}}">Login</a>
                            <li style="width:8%" class="navli"><a href="{% url 'cliente:reg' %}">Registrarse</a></li>
                        {% endif %}
                        <li style="width:24%" class="navli"><a href="#">Buscar</a>
                          <ul class="child">
                            <li>
                              <div class="input-group md-form form-sm form-1 pl-0 col-md-3">
                                <div class="input-group-prepend">
                                <span class="input-group-text purple lighten-3" id="basic-text1"><i class="fas fa-search text-white"
                                    aria-hidden="true"></i><img src="{% static '/img/header/buscar.png' %}" alt="icono de busqueda" width="20" height="20"></span>

                                <input class="form-control my-0 py-1" id="buscador" type="text" placeholder="  Buscar.." size="100" aria-label="Buscar..">
                                </div>
                              </div>
                              </li>
                            </ul>
                          </li>
                    </ul>
                </div>
            </div>
            <!--HEADER END-->

        {% block content %}
           Body content
        {% endblock %}
        <footer class="py-5 bg-dark">
            <div class="container text-center" >
                <a href="#sobreNosotros">Sobre Nosotros</a>
                <a href="#contacto">Contacto</a>
                <a href="#politicasdeprivacidad">Política de Privacidad</a>
                <a href="#derechosreservados">Políticas de Uso</a>
            </div>
            <!-- /.container -->
        </footer>
        <div class="footer">
            <p class="m-0 text-center text-white">Copyright &copy; Freak Zone 2019</p>
        </div>
    </body>
</html>